name: front-release

on:
  push:
    branches: [main, develop]
    tags:
      - "v*"

jobs:
  generate-release:
    runs-on: ubuntu-latest
    steps:
      - name: Get file name
          id: name
          run: echo "::set-output name=file_name::fga-eps-mds-2023-2-Capju-Front-$(TZ='America/Sao_Paulo' date +'%m-%d-%Y-%H-%M-%S')-${{github.ref_name}}"

      - name: Copy repository
        uses: actions/checkout@v2
      - run: wget $METRICS_URL -O ${{ steps.name.outputs.file_name }}.json
        env:
          METRICS_URL: ${{ secrets.METRICS_URL }}
      - uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.name.outputs.file_name }}.json
          path: ${{ steps.name.outputs.file_name }}.json

      - name: Commita arquivos de métricas do SonarCloud
        run: |
          git config --global user.email "${{ secrets.GIT_EMAIL }}"
          git config --global user.name "${{ secrets.GIT_USER }}"
          git clone --single-branch --branch master "https://x-access-token:${{ secrets.PERSONAL_TOKEN }}@github.com/fga-eps-mds/2023-2-CAPJu-Doc" doc
          mkdir -p doc/analytics-raw-data
          cp -R fga-eps-mds*.json doc/analytics-raw-data
          cd doc
          git add .
          git commit -m "Métricas SonarCloud - ${{ github.event.repository.name }} ${{ github.ref_name }}"
          git push
          echo "Arquivos de métricas gerado com sucesso."
